# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JayceTool' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JayceTool
pod 'IQKeyboardManager' 
pod 'JCTool', '~> 0.0.1'

end
